-- ============================================================================
-- 문의·오류 신고: 내용·답변 길이 확대(CLOB) + 이미지 첨부 테이블 (SS10 스키마에서 실행)
-- 이미 create_erp_web_feedback.sql 로 T_ERP_WEB_FEEDBACK 을 만든 경우에만 실행한다 (새로 만들 때는 create 파일만).
--
-- 1) CONTENT · ANSWER: VARCHAR2(4000) 은 바이트 기준이라 한글 약 1,333자를 넘으면 저장되지 않는다 → CLOB (앱 제한 10,000자)
--    11g 는 VARCHAR2 → CLOB 직접 변경(MODIFY)이 안 되므로 새 열에 옮기고 이름을 바꾼다. 기존 내용은 그대로 남는다.
-- 2) T_ERP_WEB_FEEDBACK_FILE: 문의당 최대 3개 이미지(PNG·JPG·GIF·WEBP, 각 5MB 이하)
-- 앱은 두 테이블이 모두 있어야 Oracle 에 저장한다 (없으면 서버 로컬 SQLite). 실행 후 1분 안에 자동 반영.
-- ============================================================================

-- 1) 내용 · 답변 → CLOB
ALTER TABLE T_ERP_WEB_FEEDBACK ADD (CONTENT_TMP CLOB, ANSWER_TMP CLOB);
UPDATE T_ERP_WEB_FEEDBACK SET CONTENT_TMP = CONTENT, ANSWER_TMP = ANSWER;
COMMIT;
ALTER TABLE T_ERP_WEB_FEEDBACK DROP (CONTENT, ANSWER);
ALTER TABLE T_ERP_WEB_FEEDBACK RENAME COLUMN CONTENT_TMP TO CONTENT;
ALTER TABLE T_ERP_WEB_FEEDBACK RENAME COLUMN ANSWER_TMP TO ANSWER;
ALTER TABLE T_ERP_WEB_FEEDBACK MODIFY (CONTENT NOT NULL);
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.CONTENT IS '내용';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.ANSWER  IS '관리자 답변';

-- 2) 첨부 이미지
CREATE TABLE T_ERP_WEB_FEEDBACK_FILE (
    FB_ID       VARCHAR2(20)    NOT NULL,
    FILE_NO     NUMBER(2)       NOT NULL,
    FILE_NM     VARCHAR2(200)   NOT NULL,
    MIME_TYPE   VARCHAR2(50)    NOT NULL,
    FILE_SIZE   NUMBER(10)      NOT NULL,
    FILE_DATA   BLOB            NOT NULL,
    INS_DAY     VARCHAR2(14)    NOT NULL,
    CONSTRAINT PK_ERP_WEB_FEEDBACK_FILE PRIMARY KEY (FB_ID, FILE_NO),
    CONSTRAINT FK_ERP_WEB_FEEDBACK_FILE FOREIGN KEY (FB_ID) REFERENCES T_ERP_WEB_FEEDBACK (FB_ID) ON DELETE CASCADE
)
LOB (FILE_DATA) STORE AS (DISABLE STORAGE IN ROW);

COMMENT ON TABLE  T_ERP_WEB_FEEDBACK_FILE           IS 'ERP 영업 관리 웹 - 문의·오류 신고 첨부 이미지 (문의당 최대 3개)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.FB_ID     IS '문의번호 (T_ERP_WEB_FEEDBACK.FB_ID)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.FILE_NO   IS '첨부 순번(1~3)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.FILE_NM   IS '원래 파일명';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.MIME_TYPE IS '이미지 형식(image/png 등, 파일 내용으로 확인)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.FILE_SIZE IS '파일 크기(바이트)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.FILE_DATA IS '이미지 데이터';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.INS_DAY   IS '등록 일시';

GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_FEEDBACK_FILE TO SS10DEV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_FEEDBACK_FILE FOR SS10.T_ERP_WEB_FEEDBACK_FILE;
