CREATE SEQUENCE SQ_SHOP_INVT_PLAN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE T_SHOP_INVT_PLAN (
    PLAN_ID             NUMBER(12)          NOT NULL,
    SHOP_ID             VARCHAR2(20)        NOT NULL,
    MO_BRD_CD           VARCHAR2(10),
    BRD_NM              VARCHAR2(50),
    SHOP_FORM_NM        VARCHAR2(100),
    SHOP_NM             VARCHAR2(200),
    PREV_SALE_AMT       NUMBER(15),
    CURR_SALE_AMT       NUMBER(15),
    ADDR                VARCHAR2(300),
    AREA_NM             VARCHAR2(30),
    REGION_NM           VARCHAR2(20),
    LAST_INVT_DT        VARCHAR2(8),
    PREV_INVT_TYPE      VARCHAR2(10),
    PREV_INVT_RESULT    NUMBER(15,2),
    STOCK_QTY           NUMBER(12),
    STOCK_BASE_DT       VARCHAR2(8),
    INVT_PLAN_NOTE      VARCHAR2(1000),
    BASE_FEE            NUMBER(12),
    EXPECT_AMT          NUMBER(12),
    INVT_PLAN_DT        VARCHAR2(8),
    RMK                 VARCHAR2(200 BYTE),
    TWICE_YEAR_YN       CHAR(1)             DEFAULT 'N' NOT NULL,
    SHOP_RANK_NM        VARCHAR2(100),
    STLM_TEAM           VARCHAR2(10),
    SMASR_NM            VARCHAR2(100),
    SMASR_HP            VARCHAR2(30),
    SHOP_TEL            VARCHAR2(30),
    INS_DAY             VARCHAR2(14)        NOT NULL,
    INS_USERID          VARCHAR2(20)        NOT NULL,
    UPT_DAY             VARCHAR2(14),
    UPT_USERID          VARCHAR2(20),
    DEL_DAY             VARCHAR2(14),
    DEL_USERID          VARCHAR2(20),
    CONSTRAINT PK_SHOP_INVT_PLAN PRIMARY KEY (PLAN_ID),
    CONSTRAINT CK_SHOP_INVT_PLAN_01 CHECK (TWICE_YEAR_YN IN ('Y', 'N')),
    CONSTRAINT CK_SHOP_INVT_PLAN_02 CHECK (PREV_INVT_TYPE IS NULL OR PREV_INVT_TYPE IN ('교체', '정기', '오픈')),
    CONSTRAINT CK_SHOP_INVT_PLAN_03 CHECK (REGION_NM IS NULL OR REGION_NM IN ('수도권', '영남권', '호남권', '충청권', '기타')),
    CONSTRAINT CK_SHOP_INVT_PLAN_04 CHECK (STLM_TEAM IS NULL OR STLM_TEAM IN ('1팀', '2팀'))
);

CREATE INDEX IX_SHOP_INVT_PLAN_01 ON T_SHOP_INVT_PLAN (SHOP_ID, DEL_DAY);
CREATE INDEX IX_SHOP_INVT_PLAN_02 ON T_SHOP_INVT_PLAN (INVT_PLAN_DT);

COMMENT ON TABLE  T_SHOP_INVT_PLAN                   IS '매장 재고 실사계획';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.PLAN_ID           IS '계획ID(SQ_SHOP_INVT_PLAN)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.SHOP_ID           IS '매장코드';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.MO_BRD_CD         IS '브랜드코드';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.BRD_NM            IS '브랜드';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.SHOP_FORM_NM      IS '유통';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.SHOP_NM           IS '매장명';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.PREV_SALE_AMT     IS '평균매출-전년(원)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.CURR_SALE_AMT     IS '평균매출-당년(원)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.ADDR              IS '주소';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.AREA_NM           IS '지역(시도)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.REGION_NM         IS '권역';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.LAST_INVT_DT      IS '최종실사일(YYYYMMDD)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.PREV_INVT_TYPE    IS '전실사유형(교체/정기/오픈)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.PREV_INVT_RESULT  IS '전실사결과';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.STOCK_QTY         IS '재고수량(당일기준)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.STOCK_BASE_DT     IS '재고수량 기준일(YYYYMMDD)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.INVT_PLAN_NOTE    IS '실사예정(자유작성)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.BASE_FEE          IS '업체예상비용-기본료';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.EXPECT_AMT        IS '업체예상비용-실사예상액';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.INVT_PLAN_DT      IS '실사예정일(YYYYMMDD, NULL=미정)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.RMK               IS '비고(200바이트)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.TWICE_YEAR_YN     IS '연2회 실사 매장 여부(Y/N)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.SHOP_RANK_NM      IS '관리등급';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.STLM_TEAM         IS '정산 팀구분(1팀/2팀)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.SMASR_NM          IS '매니저 성함';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.SMASR_HP          IS '매니저 전화번호';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.SHOP_TEL          IS '매장번호';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.INS_DAY           IS '등록일시';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.INS_USERID        IS '등록자ID';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.UPT_DAY           IS '수정일시';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.UPT_USERID        IS '수정자ID';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.DEL_DAY           IS '삭제일시(소프트삭제)';
COMMENT ON COLUMN T_SHOP_INVT_PLAN.DEL_USERID        IS '삭제자ID';
