-- ============================================================================
-- ERP 영업 관리 웹 서비스: 세션 / 로그인 잠금·기록 / AI 대화 / 즐겨찾기 / 개인 설정
-- 지금은 서버 PC 의 SQLite(backend/data/app.db)에 있는 데이터를 Oracle 로 옮기기 위한 테이블 (SS10 스키마에서 실행)
-- ============================================================================

-- 1) 로그인 세션 (1시간 슬라이딩 만료)
--    토큰 원문은 저장하지 않고 SHA-256 해시만 저장한다. (DB 가 노출돼도 세션 탈취 불가)
CREATE TABLE T_ERP_WEB_SESSION (
    TOKEN_HASH  VARCHAR2(64)    NOT NULL,
    SID         VARCHAR2(16)    NOT NULL,
    USR_ID      VARCHAR2(20)    NOT NULL,
    CREATED_TS  NUMBER(15,3)    NOT NULL,
    LAST_SEEN_TS NUMBER(15,3)   NOT NULL,
    EXPIRES_TS  NUMBER(15,3)    NOT NULL,
    IP          VARCHAR2(64),
    USER_AGENT  VARCHAR2(200),
    CONSTRAINT PK_ERP_WEB_SESSION PRIMARY KEY (TOKEN_HASH),
    CONSTRAINT UK_ERP_WEB_SESSION_01 UNIQUE (SID)
);
CREATE INDEX IX_ERP_WEB_SESSION_01 ON T_ERP_WEB_SESSION (USR_ID);
CREATE INDEX IX_ERP_WEB_SESSION_02 ON T_ERP_WEB_SESSION (EXPIRES_TS);

COMMENT ON TABLE  T_ERP_WEB_SESSION              IS 'ERP 영업 관리 웹 - 로그인 세션';
COMMENT ON COLUMN T_ERP_WEB_SESSION.TOKEN_HASH   IS '세션 토큰 SHA-256(hex). 토큰 원문은 저장하지 않음';
COMMENT ON COLUMN T_ERP_WEB_SESSION.SID          IS '관리 화면 표시용 세션ID';
COMMENT ON COLUMN T_ERP_WEB_SESSION.USR_ID       IS '사용자ID';
COMMENT ON COLUMN T_ERP_WEB_SESSION.CREATED_TS   IS '로그인 시각(유닉스 초)';
COMMENT ON COLUMN T_ERP_WEB_SESSION.LAST_SEEN_TS IS '마지막 사용 시각(유닉스 초)';
COMMENT ON COLUMN T_ERP_WEB_SESSION.EXPIRES_TS   IS '만료 시각(유닉스 초)';
COMMENT ON COLUMN T_ERP_WEB_SESSION.IP           IS '접속 IP';
COMMENT ON COLUMN T_ERP_WEB_SESSION.USER_AGENT   IS '브라우저 정보';


-- 2) 로그인 실패 누적 · 잠금 (5회 실패 시 1분)
CREATE TABLE T_ERP_WEB_LOGIN_LOCK (
    USR_ID      VARCHAR2(20)    NOT NULL,
    FAIL_CNT    NUMBER(3)       DEFAULT 0 NOT NULL,
    LOCK_TS     NUMBER(15,3)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ERP_WEB_LOGIN_LOCK PRIMARY KEY (USR_ID)
);

COMMENT ON TABLE  T_ERP_WEB_LOGIN_LOCK          IS 'ERP 영업 관리 웹 - 로그인 실패 누적/잠금';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOCK.USR_ID   IS '입력한 사용자ID';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOCK.FAIL_CNT IS '연속 실패 횟수';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOCK.LOCK_TS  IS '잠금 해제 시각(유닉스 초, 0=잠금 없음)';


-- 3) 로그인 기록
CREATE SEQUENCE SQ_ERP_WEB_LOGIN_LOG START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE TABLE T_ERP_WEB_LOGIN_LOG (
    LOG_ID      NUMBER(15)      NOT NULL,
    USR_ID      VARCHAR2(20)    NOT NULL,
    LOGIN_DAY   VARCHAR2(14)    NOT NULL,
    SUCCESS_YN  CHAR(1)         NOT NULL,
    REASON_CD   VARCHAR2(30),
    IP          VARCHAR2(64),
    CONSTRAINT PK_ERP_WEB_LOGIN_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT CK_ERP_WEB_LOGIN_LOG_01 CHECK (SUCCESS_YN IN ('Y', 'N'))
);
CREATE INDEX IX_ERP_WEB_LOGIN_LOG_01 ON T_ERP_WEB_LOGIN_LOG (USR_ID, LOGIN_DAY);
CREATE INDEX IX_ERP_WEB_LOGIN_LOG_02 ON T_ERP_WEB_LOGIN_LOG (LOGIN_DAY);

COMMENT ON TABLE  T_ERP_WEB_LOGIN_LOG            IS 'ERP 영업 관리 웹 - 로그인 기록';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOG.LOG_ID     IS '기록ID(SQ_ERP_WEB_LOGIN_LOG)';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOG.USR_ID     IS '입력한 사용자ID';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOG.LOGIN_DAY  IS '시도 일시(YYYYMMDDHH24MISS)';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOG.SUCCESS_YN IS '성공 여부';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOG.REASON_CD  IS '결과(OK/BAD_CREDENTIALS/LOCKED/INACTIVE/NOT_REGISTERED)';
COMMENT ON COLUMN T_ERP_WEB_LOGIN_LOG.IP         IS '접속 IP';


-- 4) AI 대화 기록 (사용자별)
CREATE TABLE T_ERP_WEB_AI_CONV (
    CONV_ID       VARCHAR2(40)    NOT NULL,
    USR_ID        VARCHAR2(20)    NOT NULL,
    TITLE         VARCHAR2(300),
    API_MESSAGES  CLOB,
    DISPLAY_JSON  CLOB,
    INS_DAY       VARCHAR2(14)    NOT NULL,
    UPT_DAY       VARCHAR2(14)    NOT NULL,
    CONSTRAINT PK_ERP_WEB_AI_CONV PRIMARY KEY (CONV_ID)
);
CREATE INDEX IX_ERP_WEB_AI_CONV_01 ON T_ERP_WEB_AI_CONV (USR_ID, UPT_DAY);

COMMENT ON TABLE  T_ERP_WEB_AI_CONV              IS 'ERP 영업 관리 웹 - AI 대화 기록';
COMMENT ON COLUMN T_ERP_WEB_AI_CONV.CONV_ID      IS '대화ID';
COMMENT ON COLUMN T_ERP_WEB_AI_CONV.USR_ID       IS '사용자ID';
COMMENT ON COLUMN T_ERP_WEB_AI_CONV.TITLE        IS '대화 제목(첫 질문 앞부분)';
COMMENT ON COLUMN T_ERP_WEB_AI_CONV.API_MESSAGES IS 'Claude API 메시지 기록(JSON, 이어서 질문할 때 사용)';
COMMENT ON COLUMN T_ERP_WEB_AI_CONV.DISPLAY_JSON IS '화면 표시용 대화 내용(JSON: 답변·표·차트)';
COMMENT ON COLUMN T_ERP_WEB_AI_CONV.INS_DAY      IS '시작 일시';
COMMENT ON COLUMN T_ERP_WEB_AI_CONV.UPT_DAY      IS '마지막 대화 일시';


-- 5) 즐겨찾는 질문
--    질문은 최대 500자. 같은 질문 중복 방지는 본문 대신 SHA-256 해시로 한다(인덱스 키 길이 제한 회피).
CREATE SEQUENCE SQ_ERP_WEB_AI_FAV START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE TABLE T_ERP_WEB_AI_FAV (
    FAV_ID      NUMBER(15)       NOT NULL,
    USR_ID      VARCHAR2(20)     NOT NULL,
    FAV_TEXT    VARCHAR2(2000)   NOT NULL,
    FAV_HASH    VARCHAR2(64)     NOT NULL,
    INS_DAY     VARCHAR2(14)     NOT NULL,
    CONSTRAINT PK_ERP_WEB_AI_FAV PRIMARY KEY (FAV_ID),
    CONSTRAINT UK_ERP_WEB_AI_FAV_01 UNIQUE (USR_ID, FAV_HASH)
);

COMMENT ON TABLE  T_ERP_WEB_AI_FAV          IS 'ERP 영업 관리 웹 - AI 즐겨찾는 질문';
COMMENT ON COLUMN T_ERP_WEB_AI_FAV.FAV_ID   IS '즐겨찾기ID(SQ_ERP_WEB_AI_FAV)';
COMMENT ON COLUMN T_ERP_WEB_AI_FAV.USR_ID   IS '사용자ID';
COMMENT ON COLUMN T_ERP_WEB_AI_FAV.FAV_TEXT IS '질문(최대 500자)';
COMMENT ON COLUMN T_ERP_WEB_AI_FAV.FAV_HASH IS '질문 SHA-256(hex), 중복 방지용';
COMMENT ON COLUMN T_ERP_WEB_AI_FAV.INS_DAY  IS '등록일시';


-- 6) 개인 화면 설정 (표시 컬럼 등, 값은 JSON)
CREATE TABLE T_ERP_WEB_USER_PREF (
    USR_ID      VARCHAR2(20)     NOT NULL,
    PREF_KEY    VARCHAR2(100)    NOT NULL,
    PREF_VAL    VARCHAR2(4000),
    UPT_DAY     VARCHAR2(14)     NOT NULL,
    CONSTRAINT PK_ERP_WEB_USER_PREF PRIMARY KEY (USR_ID, PREF_KEY)
);

COMMENT ON TABLE  T_ERP_WEB_USER_PREF          IS 'ERP 영업 관리 웹 - 개인 화면 설정';
COMMENT ON COLUMN T_ERP_WEB_USER_PREF.USR_ID   IS '사용자ID';
COMMENT ON COLUMN T_ERP_WEB_USER_PREF.PREF_KEY IS '설정키(예: detail.columns)';
COMMENT ON COLUMN T_ERP_WEB_USER_PREF.PREF_VAL IS '설정값(JSON)';
COMMENT ON COLUMN T_ERP_WEB_USER_PREF.UPT_DAY  IS '수정일시';


-- 7) 앱 계정(SS10DEV) 권한 · 시노님
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_SESSION    TO SS10DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_LOGIN_LOCK TO SS10DEV;
GRANT SELECT, INSERT, DELETE         ON T_ERP_WEB_LOGIN_LOG  TO SS10DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_AI_CONV    TO SS10DEV;
GRANT SELECT, INSERT, DELETE         ON T_ERP_WEB_AI_FAV     TO SS10DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_USER_PREF  TO SS10DEV;
GRANT SELECT ON SQ_ERP_WEB_LOGIN_LOG TO SS10DEV;
GRANT SELECT ON SQ_ERP_WEB_AI_FAV    TO SS10DEV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_SESSION    FOR SS10.T_ERP_WEB_SESSION;
CREATE SYNONYM SS10DEV.T_ERP_WEB_LOGIN_LOCK FOR SS10.T_ERP_WEB_LOGIN_LOCK;
CREATE SYNONYM SS10DEV.T_ERP_WEB_LOGIN_LOG  FOR SS10.T_ERP_WEB_LOGIN_LOG;
CREATE SYNONYM SS10DEV.T_ERP_WEB_AI_CONV    FOR SS10.T_ERP_WEB_AI_CONV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_AI_FAV     FOR SS10.T_ERP_WEB_AI_FAV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_USER_PREF  FOR SS10.T_ERP_WEB_USER_PREF;
CREATE SYNONYM SS10DEV.SQ_ERP_WEB_LOGIN_LOG FOR SS10.SQ_ERP_WEB_LOGIN_LOG;
CREATE SYNONYM SS10DEV.SQ_ERP_WEB_AI_FAV    FOR SS10.SQ_ERP_WEB_AI_FAV;
