-- ============================================================================
-- ERP 영업 관리 웹 서비스: 사용자 권한 / 한도 / 전역 설정 (SS10 스키마에서 실행)
-- ============================================================================

-- 1) 사용자 권한 · AI 한도
CREATE TABLE T_ERP_WEB_USER (
    USR_ID          VARCHAR2(20)                NOT NULL,
    USR_NM          VARCHAR2(100),
    ROLE_CD         VARCHAR2(10)  DEFAULT 'USER' NOT NULL,
    AI_USE_YN       CHAR(1)       DEFAULT 'Y'    NOT NULL,
    DAY_QSTN_LMT    NUMBER(5),
    DAY_COST_LMT    NUMBER(10,2),
    USE_YN          CHAR(1)       DEFAULT 'Y'    NOT NULL,
    LAST_LOGIN_DAY  VARCHAR2(14),
    INS_DAY         VARCHAR2(14)                NOT NULL,
    INS_USERID      VARCHAR2(20)                NOT NULL,
    UPT_DAY         VARCHAR2(14),
    UPT_USERID      VARCHAR2(20),
    CONSTRAINT PK_ERP_WEB_USER PRIMARY KEY (USR_ID),
    CONSTRAINT CK_ERP_WEB_USER_01 CHECK (ROLE_CD IN ('ADMIN', 'USER')),
    CONSTRAINT CK_ERP_WEB_USER_02 CHECK (AI_USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_ERP_WEB_USER_03 CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_ERP_WEB_USER_04 CHECK (DAY_QSTN_LMT IS NULL OR DAY_QSTN_LMT BETWEEN 0 AND 1000),
    CONSTRAINT CK_ERP_WEB_USER_05 CHECK (DAY_COST_LMT IS NULL OR DAY_COST_LMT BETWEEN 0 AND 1000)
);

COMMENT ON TABLE  T_ERP_WEB_USER                IS 'ERP 영업 관리 웹 - 사용자 권한/AI 한도';
COMMENT ON COLUMN T_ERP_WEB_USER.USR_ID         IS '사용자ID(T_USR.USR_ID)';
COMMENT ON COLUMN T_ERP_WEB_USER.USR_NM         IS '사용자명(로그인 시 T_USR 에서 갱신)';
COMMENT ON COLUMN T_ERP_WEB_USER.ROLE_CD        IS '권한(ADMIN/USER)';
COMMENT ON COLUMN T_ERP_WEB_USER.AI_USE_YN      IS 'AI 사용 여부(Y/N)';
COMMENT ON COLUMN T_ERP_WEB_USER.DAY_QSTN_LMT   IS 'AI 일일 질문 한도(NULL=전역 기본값)';
COMMENT ON COLUMN T_ERP_WEB_USER.DAY_COST_LMT   IS 'AI 일일 비용 한도 USD(NULL=전역 기본값)';
COMMENT ON COLUMN T_ERP_WEB_USER.USE_YN         IS '계정 사용 여부(Y/N, N=로그인 차단)';
COMMENT ON COLUMN T_ERP_WEB_USER.LAST_LOGIN_DAY IS '최근 로그인 일시';
COMMENT ON COLUMN T_ERP_WEB_USER.INS_DAY        IS '등록일시';
COMMENT ON COLUMN T_ERP_WEB_USER.INS_USERID     IS '등록자ID(자동 등록 시 본인)';
COMMENT ON COLUMN T_ERP_WEB_USER.UPT_DAY        IS '수정일시';
COMMENT ON COLUMN T_ERP_WEB_USER.UPT_USERID     IS '수정자ID';


-- 2) 사용자별 페이지(메뉴) 권한
CREATE TABLE T_ERP_WEB_USER_PAGE (
    USR_ID      VARCHAR2(20)  NOT NULL,
    PAGE_CD     VARCHAR2(30)  NOT NULL,
    INS_DAY     VARCHAR2(14)  NOT NULL,
    INS_USERID  VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_ERP_WEB_USER_PAGE PRIMARY KEY (USR_ID, PAGE_CD),
    CONSTRAINT FK_ERP_WEB_USER_PAGE_01 FOREIGN KEY (USR_ID) REFERENCES T_ERP_WEB_USER (USR_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  T_ERP_WEB_USER_PAGE            IS 'ERP 영업 관리 웹 - 사용자별 페이지 권한';
COMMENT ON COLUMN T_ERP_WEB_USER_PAGE.USR_ID     IS '사용자ID';
COMMENT ON COLUMN T_ERP_WEB_USER_PAGE.PAGE_CD    IS '페이지코드(dashboard/detail/sale_monthly/invt_plan)';
COMMENT ON COLUMN T_ERP_WEB_USER_PAGE.INS_DAY    IS '부여일시';
COMMENT ON COLUMN T_ERP_WEB_USER_PAGE.INS_USERID IS '부여자ID';


-- 3) 전역 설정 (AI 기본 한도 · 모델 등)
CREATE TABLE T_ERP_WEB_SETTING (
    SET_KEY     VARCHAR2(50)    NOT NULL,
    SET_VAL     VARCHAR2(1000),
    SET_DESC    VARCHAR2(200),
    UPT_DAY     VARCHAR2(14),
    UPT_USERID  VARCHAR2(20),
    CONSTRAINT PK_ERP_WEB_SETTING PRIMARY KEY (SET_KEY)
);

COMMENT ON TABLE  T_ERP_WEB_SETTING            IS 'ERP 영업 관리 웹 - 전역 설정';
COMMENT ON COLUMN T_ERP_WEB_SETTING.SET_KEY    IS '설정키';
COMMENT ON COLUMN T_ERP_WEB_SETTING.SET_VAL    IS '설정값(NULL=.env 기본값 사용)';
COMMENT ON COLUMN T_ERP_WEB_SETTING.SET_DESC   IS '설명';
COMMENT ON COLUMN T_ERP_WEB_SETTING.UPT_DAY    IS '수정일시';
COMMENT ON COLUMN T_ERP_WEB_SETTING.UPT_USERID IS '수정자ID';

INSERT INTO T_ERP_WEB_SETTING (SET_KEY, SET_VAL, SET_DESC) VALUES ('AI_ENABLED',           'Y',  'AI 대화 기능 사용(Y/N)');
INSERT INTO T_ERP_WEB_SETTING (SET_KEY, SET_VAL, SET_DESC) VALUES ('DEFAULT_DAY_QSTN_LMT', '10', '사용자 기본 일일 질문 한도');
INSERT INTO T_ERP_WEB_SETTING (SET_KEY, SET_VAL, SET_DESC) VALUES ('DEFAULT_DAY_COST_LMT', '2',  '사용자 기본 일일 비용 한도(USD)');
INSERT INTO T_ERP_WEB_SETTING (SET_KEY, SET_VAL, SET_DESC) VALUES ('AI_MODEL',             NULL, 'Claude 모델(NULL=.env ANTHROPIC_MODEL)');
INSERT INTO T_ERP_WEB_SETTING (SET_KEY, SET_VAL, SET_DESC) VALUES ('AI_EFFORT',            NULL, '사고 강도(NULL=.env ANTHROPIC_EFFORT)');
COMMIT;


-- 4) 앱 계정(SS10DEV) 권한 · 시노님
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_USER      TO SS10DEV;
GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_USER_PAGE TO SS10DEV;
GRANT SELECT, INSERT, UPDATE         ON T_ERP_WEB_SETTING   TO SS10DEV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_USER      FOR SS10.T_ERP_WEB_USER;
CREATE SYNONYM SS10DEV.T_ERP_WEB_USER_PAGE FOR SS10.T_ERP_WEB_USER_PAGE;
CREATE SYNONYM SS10DEV.T_ERP_WEB_SETTING   FOR SS10.T_ERP_WEB_SETTING;
