-- ============================================================================
-- ERP 영업 관리 웹 서비스: AI 사용량 (일일 한도 계산 · 사용 현황) (SS10 스키마에서 실행)
-- 1행 = 질문 1건(USE_TYPE='Q') 또는 Claude API 호출 1회(USE_TYPE='C')
-- ============================================================================
CREATE SEQUENCE SQ_ERP_WEB_AI_USAGE START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE TABLE T_ERP_WEB_AI_USAGE (
    USAGE_ID        NUMBER(15)      NOT NULL,
    USR_ID          VARCHAR2(20)    NOT NULL,
    USE_DT          VARCHAR2(8)     NOT NULL,
    USE_DAY         VARCHAR2(14)    NOT NULL,
    USE_TYPE        CHAR(1)         NOT NULL,
    CONV_ID         VARCHAR2(40),
    MODEL_NM        VARCHAR2(50),
    INPUT_TOKENS    NUMBER(12)      DEFAULT 0 NOT NULL,
    OUTPUT_TOKENS   NUMBER(12)      DEFAULT 0 NOT NULL,
    CACHE_READ      NUMBER(12)      DEFAULT 0 NOT NULL,
    CACHE_WRITE     NUMBER(12)      DEFAULT 0 NOT NULL,
    COST_USD        NUMBER(12,6)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ERP_WEB_AI_USAGE PRIMARY KEY (USAGE_ID),
    CONSTRAINT CK_ERP_WEB_AI_USAGE_01 CHECK (USE_TYPE IN ('Q', 'C'))
);

CREATE INDEX IX_ERP_WEB_AI_USAGE_01 ON T_ERP_WEB_AI_USAGE (USR_ID, USE_DT);
CREATE INDEX IX_ERP_WEB_AI_USAGE_02 ON T_ERP_WEB_AI_USAGE (USE_DT);

COMMENT ON TABLE  T_ERP_WEB_AI_USAGE               IS 'ERP 영업 관리 웹 - AI 사용량';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.USAGE_ID      IS '사용ID(SQ_ERP_WEB_AI_USAGE)';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.USR_ID        IS '사용자ID';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.USE_DT        IS '사용일자(YYYYMMDD, 일일 한도 기준)';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.USE_DAY       IS '사용일시(YYYYMMDDHH24MISS)';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.USE_TYPE      IS '구분(Q=질문, C=API 호출)';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.CONV_ID       IS '대화ID';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.MODEL_NM      IS '응답 모델';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.INPUT_TOKENS  IS '입력 토큰';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.OUTPUT_TOKENS IS '출력 토큰';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.CACHE_READ    IS '캐시 읽기 토큰';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.CACHE_WRITE   IS '캐시 쓰기 토큰';
COMMENT ON COLUMN T_ERP_WEB_AI_USAGE.COST_USD      IS '비용(USD)';

GRANT SELECT, INSERT, DELETE ON T_ERP_WEB_AI_USAGE TO SS10DEV;
GRANT SELECT ON SQ_ERP_WEB_AI_USAGE TO SS10DEV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_AI_USAGE FOR SS10.T_ERP_WEB_AI_USAGE;
CREATE SYNONYM SS10DEV.SQ_ERP_WEB_AI_USAGE FOR SS10.SQ_ERP_WEB_AI_USAGE;
