-- ============================================================================
-- ERP 영업 관리 웹 서비스: 관리자 변경 이력 (관리자 › 변경 이력) (SS10 스키마에서 실행)
-- 테이블이 없으면 앱은 서버 로컬(SQLite)에 기록하고, 이 테이블을 만들면 1분 안에 자동으로 옮겨 쓴다(재시작 불필요).
-- ============================================================================

CREATE SEQUENCE SQ_ERP_WEB_ADMIN_LOG START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

CREATE TABLE T_ERP_WEB_ADMIN_LOG (
    LOG_ID       NUMBER(15)      NOT NULL,
    LOG_DAY      VARCHAR2(14)    NOT NULL,
    ADMIN_ID     VARCHAR2(20)    NOT NULL,
    ACTION_CD    VARCHAR2(30)    NOT NULL,
    TARGET       VARCHAR2(100),
    SUMMARY      VARCHAR2(4000),
    BEFORE_JSON  CLOB,
    AFTER_JSON   CLOB,
    IP           VARCHAR2(64),
    CONSTRAINT PK_ERP_WEB_ADMIN_LOG PRIMARY KEY (LOG_ID)
);
CREATE INDEX IX_ERP_WEB_ADMIN_LOG_01 ON T_ERP_WEB_ADMIN_LOG (LOG_DAY);
CREATE INDEX IX_ERP_WEB_ADMIN_LOG_02 ON T_ERP_WEB_ADMIN_LOG (TARGET, LOG_DAY);

COMMENT ON TABLE  T_ERP_WEB_ADMIN_LOG             IS 'ERP 영업 관리 웹 - 관리자 변경 이력';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.LOG_ID      IS '이력ID(SQ_ERP_WEB_ADMIN_LOG)';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.LOG_DAY     IS '변경 일시(YYYYMMDDHH24MISS)';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.ADMIN_ID    IS '변경한 관리자ID';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.ACTION_CD   IS '작업(USER_CREATE/USER_UPDATE/PERM_UPDATE/SETTING_UPDATE/TOOL_*/LOCK_RELEASE/SESSION_KILL)';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.TARGET      IS '대상(사용자ID, 도구 이름 등)';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.SUMMARY     IS '변경 요약(항목: 이전 → 이후)';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.BEFORE_JSON IS '변경 전 값(JSON)';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.AFTER_JSON  IS '변경 후 값(JSON)';
COMMENT ON COLUMN T_ERP_WEB_ADMIN_LOG.IP          IS '관리자 접속 IP';

-- 이력은 추가·조회만 한다 (수정·삭제 권한을 주지 않아 앱에서 이력을 고칠 수 없음)
GRANT SELECT, INSERT ON T_ERP_WEB_ADMIN_LOG TO SS10DEV;
GRANT SELECT ON SQ_ERP_WEB_ADMIN_LOG TO SS10DEV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_ADMIN_LOG FOR SS10.T_ERP_WEB_ADMIN_LOG;
CREATE SYNONYM SS10DEV.SQ_ERP_WEB_ADMIN_LOG FOR SS10.SQ_ERP_WEB_ADMIN_LOG;
