-- ============================================================================
-- ERP 영업 관리 웹 서비스: 화면 내 문의·오류 신고 (SS10 스키마에서 실행)
--
-- 사용자가 화면 오른쪽 위 [문의·신고] 로 남긴 내용과 그때의 화면·조회 조건·최근 오류(CTX_JSON),
-- 관리자의 처리 상태·답변 (관리자 › 문의·신고).
-- 첨부 이미지는 T_ERP_WEB_FEEDBACK_FILE (문의당 최대 3개). 이미 예전 판으로 만들었다면 alter_erp_web_feedback_files.sql 만 실행.
-- 두 테이블이 없으면 서버 로컬(SQLite)에 저장하고, 만들면 1분 안에 Oracle 을 쓰며 그동안의 기록을 한 번 옮긴다.
-- ============================================================================

CREATE TABLE T_ERP_WEB_FEEDBACK (
    FB_ID       VARCHAR2(20)    NOT NULL,
    USR_ID      VARCHAR2(20)    NOT NULL,
    USR_NM      VARCHAR2(100),
    FB_TYPE     VARCHAR2(10)    NOT NULL,
    CONTENT     CLOB            NOT NULL,
    PAGE_CD     VARCHAR2(30),
    CTX_JSON    VARCHAR2(4000),
    STATUS      VARCHAR2(10)    DEFAULT 'NEW' NOT NULL,
    ANSWER      CLOB,
    ANSWER_USR  VARCHAR2(20),
    ANSWER_DAY  VARCHAR2(14),
    INS_DAY     VARCHAR2(14)    NOT NULL,
    UPT_DAY     VARCHAR2(14)    NOT NULL,
    CONSTRAINT PK_ERP_WEB_FEEDBACK PRIMARY KEY (FB_ID)
);

CREATE INDEX IX_ERP_WEB_FEEDBACK_01 ON T_ERP_WEB_FEEDBACK (USR_ID, INS_DAY);
CREATE INDEX IX_ERP_WEB_FEEDBACK_02 ON T_ERP_WEB_FEEDBACK (STATUS, INS_DAY);

COMMENT ON TABLE  T_ERP_WEB_FEEDBACK            IS 'ERP 영업 관리 웹 - 화면 내 문의·오류 신고';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.FB_ID      IS '문의번호(접수일시 14자리 + 난수 4자리)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.USR_ID     IS '작성 사용자ID';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.USR_NM     IS '작성 사용자명';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.FB_TYPE    IS '구분(BUG 오류 / REQ 요청 / ASK 문의)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.CONTENT    IS '내용';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.PAGE_CD    IS '작성 당시 메뉴코드';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.CTX_JSON   IS '작성 당시 화면·조회 조건·최근 오류(JSON, 자동 첨부)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.STATUS     IS '상태(NEW 접수 / DOING 처리 중 / DONE 완료)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.ANSWER     IS '관리자 답변';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.ANSWER_USR IS '답변 관리자ID';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.ANSWER_DAY IS '답변 일시';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.INS_DAY    IS '접수 일시';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK.UPT_DAY    IS '수정 일시';

GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_FEEDBACK TO SS10DEV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_FEEDBACK FOR SS10.T_ERP_WEB_FEEDBACK;

CREATE TABLE T_ERP_WEB_FEEDBACK_FILE (
    FB_ID       VARCHAR2(20)    NOT NULL,
    FILE_NO     NUMBER(2)       NOT NULL,
    FILE_NM     VARCHAR2(200)   NOT NULL,
    MIME_TYPE   VARCHAR2(50)    NOT NULL,
    FILE_SIZE   NUMBER(10)      NOT NULL,
    FILE_DATA   BLOB            NOT NULL,
    INS_DAY     VARCHAR2(14)    NOT NULL,
    CONSTRAINT PK_ERP_WEB_FEEDBACK_FILE PRIMARY KEY (FB_ID, FILE_NO),
    CONSTRAINT FK_ERP_WEB_FEEDBACK_FILE FOREIGN KEY (FB_ID) REFERENCES T_ERP_WEB_FEEDBACK (FB_ID) ON DELETE CASCADE
)
LOB (FILE_DATA) STORE AS (DISABLE STORAGE IN ROW);

COMMENT ON TABLE  T_ERP_WEB_FEEDBACK_FILE           IS 'ERP 영업 관리 웹 - 문의·오류 신고 첨부 이미지 (문의당 최대 3개)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.FILE_NO   IS '첨부 순번(1~3)';
COMMENT ON COLUMN T_ERP_WEB_FEEDBACK_FILE.MIME_TYPE IS '이미지 형식(image/png 등, 파일 내용으로 확인)';

GRANT SELECT, INSERT, UPDATE, DELETE ON T_ERP_WEB_FEEDBACK_FILE TO SS10DEV;
CREATE SYNONYM SS10DEV.T_ERP_WEB_FEEDBACK_FILE FOR SS10.T_ERP_WEB_FEEDBACK_FILE;
